INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:JobQueue:An uncaught error was raised while executing job send_updates
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 418, in tick
    job.run(self._dispatcher)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 574, in run
    self.callback(CallbackContext.from_job(self, dispatcher))
TypeError: send_updates() missing 1 required positional argument: 'context'
ERROR:JobQueue:An uncaught error was raised while executing job send_updates
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 418, in tick
    job.run(self._dispatcher)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 574, in run
    self.callback(CallbackContext.from_job(self, dispatcher))
TypeError: send_updates() missing 1 required positional argument: 'context'
ERROR:JobQueue:An uncaught error was raised while executing job send_updates
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 418, in tick
    job.run(self._dispatcher)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 574, in run
    self.callback(CallbackContext.from_job(self, dispatcher))
TypeError: send_updates() missing 1 required positional argument: 'context'
ERROR:JobQueue:An uncaught error was raised while executing job send_updates
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 418, in tick
    job.run(self._dispatcher)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 574, in run
    self.callback(CallbackContext.from_job(self, dispatcher))
TypeError: send_updates() missing 1 required positional argument: 'context'
ERROR:JobQueue:An uncaught error was raised while executing job send_updates
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 418, in tick
    job.run(self._dispatcher)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 574, in run
    self.callback(CallbackContext.from_job(self, dispatcher))
TypeError: send_updates() missing 1 required positional argument: 'context'
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
INFO:root:Бот стартовал
ERROR:JobQueue:An uncaught error was raised while executing job send_updates
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 418, in tick
    job.run(self._dispatcher)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 574, in run
    self.callback(CallbackContext.from_job(self, dispatcher))
TypeError: send_updates() missing 1 required positional argument: 'context'
ERROR:JobQueue:An uncaught error was raised while executing job send_updates
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 418, in tick
    job.run(self._dispatcher)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 574, in run
    self.callback(CallbackContext.from_job(self, dispatcher))
TypeError: send_updates() missing 1 required positional argument: 'context'
ERROR:JobQueue:An uncaught error was raised while executing job send_updates
Traceback (most recent call last):
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 418, in tick
    job.run(self._dispatcher)
  File "c:\projects\bot_diplom\env\lib\site-packages\telegram\ext\jobqueue.py", line 574, in run
    self.callback(CallbackContext.from_job(self, dispatcher))
TypeError: send_updates() missing 1 required positional argument: 'context'
INFO:telegram.ext.updater:Received signal 2 (SIGINT), stopping...
WARNING:telegram.ext.updater:Exiting immediately!
